N_CLUSTERS = 5

STRING_COLS = ["Team", "Game", "Date", "Home", "Opponent", "WINorLOSS", "cluster"]

NUMERIC_COLS = [
    "TeamPoints",
    "OpponentPoints",
    "FieldGoals",
    "FieldGoalsAttempted",
    "FieldGoals.",
    "X3PointShots",
    "X3PointShotsAttempted",
    "X3PointShots.",
    "FreeThrows",
    "FreeThrowsAttempted",
    "FreeThrows.",
    "OffRebounds",
    "TotalRebounds",
    "Assists",
    "Steals",
    "Blocks",
    "Turnovers",
    "TotalFouls",
    "Opp.FieldGoals",
    "Opp.FieldGoalsAttempted",
    "Opp.FieldGoals.",
    "Opp.3PointShots",
    "Opp.3PointShotsAttempted",
    "Opp.3PointShots.",
    "Opp.FreeThrows",
    "Opp.FreeThrowsAttempted",
    "Opp.FreeThrows.",
    "Opp.OffRebounds",
    "Opp.TotalRebounds",
    "Opp.Assists",
    "Opp.Steals",
    "Opp.Blocks",
    "Opp.Turnovers",
    "Opp.TotalFouls",
]
